### ISSUE TITLE
Write unit-tests for AccountService, UserService methods in db_service.py

### ISSUE THREAD

**Issue by th4ruka** [CeyLabs-Foundation/fin-tracker-backend#3]
## Description:
* Create unit tests for `AccountService` and `UserService` classes in `/app/services/db_service.py`.

## TODO:
 * [x] Install `pytest` as the testing framework.
 * [x] Create a separate `/tests` directory inside project root.
 * Follow the same project structure as in the `/app` directory to create tests:
 ```
/app/
--/models
--/services
...
/tests/
--/models
--/services
...
```

 * [x] Write tests for functions of `UserService`, `AccountService`.
 * [x] Execute and validate test cases.

**Comment by sahild91** [comment]
Hi,
I can try contributing towards the test cases to help you.

**Comment by th4ruka** [comment]
> Hi, I can try contributing towards the test cases to help you.

Yes @sahild91, you can go ahead.

1. Fork this repository to your GitHub.
2. Create a separate branch & write test cases in it.
3. After you have done, push it to your forked repository.
4. Finally, make a pull request to this repo from your branch.

**Comment by sahild91** [comment]
@th4ruka ,
I have added the test cases and created a pull request. Please review it once and let me know if you need any changes on it.
https://github.com/CeyLabs-Foundation/fin-tracker-backend/pull/6
